config/routes.rb
Rails.application.routes.draw do
  get '/hello', to: 'static_pages#hello'
  get '/about', to: 'static_pages#about'
  get '/sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#hello'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 200 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, world"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user.present? && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to_stored_url(user)
    else
      render "new"
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def hello
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  include SessionsHelper
  
  def index
    @users = User.all.page(params[:page]).per(10)
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録に成功しました"
      redirect_to @user
    else
      flash.now[:danger] = "登録に失敗しました"
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    @user.assign_attributes(user_params)
    if @user.save
      flash[:success] = "更新に成功しました"
      redirect_to @user
    else
      flash.now[:danger] = "更新に失敗しました"
      render "edit"
    end
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy!
    redirect_to users_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def logged_in_user
    unless logged_in?
      store_url
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find_by(id: params[:id])
    if current_user != @user
      flash[:danger] = '他人のユーザー情報を編集することはできません'
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    default_title = "StaticApp"
    title.blank? ? default_title : "#{title} | #{default_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id].present?
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    current_user.present?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = session
  end
  
  def store_url
    session[:forwarding_url] = request.original_url
  end
  
  def redirect_to_stored_url(user)
    redirect_to session[:forwarding_url] || user
    session.delete(:forwarding_url)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p>@made in KAZUHIKO</p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/html5shiv' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md bg-dark text-white fixed-top">
  <div class="container">
    <%= link_to "Static App", root_path, id: "logo" %>
    <nav>
      <ul class="navbar-nav nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "My page", user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", sign_up_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_html5shiv.html.erb
<!--[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container under-header">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="top">
  <p>About page</p>
</div>

app/views/static_pages/hello.html.erb
<% provide(:title, "Hello") %>
<div class="top">
  <h1>読んだ本を記憶に残しておくために！！</h1><br>
  <h2>読んだ本を管理するシステムです。<br><br>
  人間は忘れる生き物です。<br><br>
  苦労して読んだ本から学んだ知識を忘れてしまってはもったいない。<br><br>
  読んだ本の要点や感想等を保存しておき、定期的に見直すことにより記憶にとどめる事ができます。<br><br>
  たくさん本を読み、たくさんの知識を蓄え、人生をより豊かにして行こう！！
  </h2>
</div>
<% # TODO: 後で消す %>
<%= link_to image_tag("SamplePenguin.jpg", alt: "SamplePenguin"), "#" %>

app/views/users/_user.html.erb
<p><%= user.name %></p>
<p><%= user.email %></p>

app/views/users/edit.html.erb
<%= render 'shared/user_error_messages' %>
<div class="top">
  <p>ユーザー更新ページ</p>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name, "氏名" %>
      <%= f.text_field :name %>
      
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>
      
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "アカウント更新", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="top">
  <p>ユーザー一覧ページ</p>
  <%= render @users %>
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<%= render 'shared/user_error_messages' %>
<div class="top">
  <p>ユーザー登録ページ</p>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true, url: sign_up_path) do |f| %>
      <%= f.label :name, "氏名" %>
      <%= f.text_field :name %>
      
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email %>
      
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password %>
      
      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "アカウント登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="top">
  <p>ユーザー詳細ページ</p>
  <%= render @user %>
  <% if current_user == @user %>
    <p><%= link_to "ユーザー情報編集", edit_user_path %></p>
  <% end %>
  <p><%= link_to "ユーザー削除", @user, methhod: :delete, data: { confirm: "ユーザー情報を削除しますか？" } %></p>
</div>